<?php

include 'conn.php';
session_start();

$recipe_name = $_POST['recipe_name'];
$ingredient_name = $_POST['ingredient_name'];
$steps = $_POST['steps'];
$name = $_POST['category'];

$rng = uniqid('',true);

// Gets userID from database based on login user's email
$sql = "SELECT user_id FROM login WHERE email = '" . $_SESSION['login_user'] . "'";
$result = mysqli_query($conn, $sql);
$user_id = mysqli_fetch_row($result)[0];
mysqli_free_result($result);

// Inserts user_id and recipe_name to Recipes, recipe_id is autogenerated
$target_dir = "uploads/";
$target_file = $target_dir . basename($_FILES["uploadfile"]["name"]);
$filename = str_replace(" ", "_", $_FILES["uploadfile"]["name"]);
$filetype = explode(".", $filename);
$target_rng = $target_dir . $rng . "." . end($filetype);
$upload_name = $rng . "." . end($filetype);
move_uploaded_file($_FILES["uploadfile"]["tmp_name"], $target_file);
rename ($target_file, $target_rng);

// Get all the submitted data from the form
$sql = "INSERT INTO `Recipes` (`user_id`, `recipe_name`, `filename`, `ingredient_name`, `steps`) VALUES ($user_id, '$recipe_name','$upload_name', '$ingredient_name', '$steps')";
$result = mysqli_query($conn, $sql);


// Gets autogenerated recipe_id from LAST_INSERT_ID() MySql Function
$sql = "SELECT LAST_INSERT_ID()";
$result = mysqli_query($conn, $sql);
$recipe_id = mysqli_fetch_row($result)[0]; // echo and double check if matches db.
mysqli_free_result($result);


// Loads recipe_id | category_id TABLE
/* 
    $_POST['category'] doesn't exist if checkbox unticked
    $categories is $_POST['category'] array if isset, and empty array array() if !isset

    Then, iterate over $categories to INSERT INTO db
*/
$sql = "SELECT * FROM category";
$result = mysqli_query($conn, $sql);

$array = array();

// mysqli_fetch_array should return null and quits loop if can't find next $row
while($row = mysqli_fetch_array($result)) {
    // mysqli_fetch_array returns k, v pairs category_id => INT and category_name => STRING
    // loads into $array = [ category_name => category_id ]
    $array[$row["category_name"]] = $row["category_id"];
}

// Purpose: recipe ID | category_ID
$categories = isset($_POST['category']) ? $_POST['category'] : array();
foreach ($categories as $categoryName) {
    $category_id = $array[$categoryName];
    $sql = "INSERT INTO category_input (`recipe_id`, `category_id`) VALUES ($recipe_id, $category_id)";
    $result = mysqli_query($conn, $sql);

}
?> 
